In [11]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import os
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [12]:
path = r"C:\Users\Noble Adike\Desktop\Coding\KPMG\kpmg-1a\data\harvard\Year 2 (Jun 2023 - May 2024)\CO2_hourly\48190915_CO2_hourly.csv"
df = pd.read_csv(path)

In [13]:
df.head()

,Timestamp,Z11_CO2 (ppm),Z12+13_CO2 (ppm),Z15+16_CO2 (ppm),Z17_CO2 (ppm),Z1_CO2 (ppm),Z21_CO2 (ppm),Z22+23_CO2 (ppm),Z24_CO2 (ppm),Z25+26+27_CO2 (ppm),Z31_CO2 (ppm),Z32_CO2 (ppm),Z33_CO2 (ppm),Z3_CO2 (ppm),Z4_CO2 (ppm),Z5_CO2 (ppm)
0,2023-06-01 00:00:00-04:00,429.541334,427.392003,441.568003,506.863995,428.410666,438.501334,429.168000,567.898673,427.621335,390.079987,456.917332,439.029332,621.141328,528.165325,463.018667
1,2023-06-01 01:00:00-04:00,434.101333,432.133334,443.242666,481.210664,428.122667,439.296000,427.770671,571.850667,427.013337,390.079987,445.530665,435.626666,620.709338,562.837337,441.077333
2,2023-06-01 02:00:00-04:00,437.338664,432.687999,448.042666,466.655999,433.589335,438.463999,429.797331,580.581333,429.941335,390.079987,437.973332,431.557334,587.264005,528.800003,450.293334
3,2023-06-01 03:00:00-04:00,434.698666,437.424000,446.890670,452.234664,437.669332,440.576003,428.922672,521.434668,426.303999,390.079987,432.293333,432.325336,542.261336,497.327997,466.597329
4,2023-06-01 04:00:00-04:00,440.042670,443.173334,445.621335,446.442667,439.669333,437.797332,426.463999,498.277338,427.429332,390.079987,430.474669,433.733333,521.626674,485.141336,468.874667

In [14]:
df.isna().sum()

Timestamp              0
Z11_CO2 (ppm)          4
Z12+13_CO2 (ppm)       2
Z15+16_CO2 (ppm)       1
Z17_CO2 (ppm)          2
Z1_CO2 (ppm)           2
Z21_CO2 (ppm)          0
Z22+23_CO2 (ppm)       5
Z24_CO2 (ppm)          3
Z25+26+27_CO2 (ppm)    0
Z31_CO2 (ppm)          0
Z32_CO2 (ppm)          5
Z33_CO2 (ppm)          0
Z3_CO2 (ppm)           2
Z4_CO2 (ppm)           2
Z5_CO2 (ppm)           0
dtype: int64

In [15]:
df.describe()

,Z11_CO2 (ppm),Z12+13_CO2 (ppm),Z15+16_CO2 (ppm),Z17_CO2 (ppm),Z1_CO2 (ppm),Z21_CO2 (ppm),Z22+23_CO2 (ppm),Z24_CO2 (ppm),Z25+26+27_CO2 (ppm),Z31_CO2 (ppm),Z32_CO2 (ppm),Z33_CO2 (ppm),Z3_CO2 (ppm),Z4_CO2 (ppm),Z5_CO2 (ppm)
count,8780.000000,8782.000000,8783.000000,8782.000000,8782.000000,8784.000000,8779.000000,8781.000000,8784.000000,8784.000000,8779.000000,8784.000000,8782.000000,8782.000000,8784.000000
mean,519.621108,519.156744,532.051374,514.547102,529.910073,565.887975,540.280400,597.272671,544.487987,461.294962,523.624869,547.492869,519.842436,518.068645,512.956124
std,127.787368,123.267047,129.362959,118.874998,140.024069,188.645910,153.727509,134.884815,160.928571,127.810179,134.261117,179.685250,100.923286,109.042630,107.718235
min,372.496284,392.138658,392.320007,393.546666,390.570655,391.039987,390.479988,329.133568,346.267136,367.282759,393.925331,391.735990,391.557322,390.997322,392.445323
25%,437.378669,434.740001,446.378667,433.618669,442.382667,434.545335,431.774667,498.389331,435.829336,390.079987,432.792002,436.378666,451.864000,445.297336,436.699999
50%,471.856004,473.058670,485.781336,471.600002,486.024001,492.231999,480.602664,575.813336,482.073332,392.610659,476.058663,483.202665,487.671997,481.368000,473.941333
75%,558.806666,566.374675,572.746665,551.910672,568.919994,632.828002,599.434666,670.101341,593.294677,482.823999,569.637331,595.522665,554.605338,552.328003,560.019996
max,1786.037893,1674.273698,1677.911592,1563.688422,2843.415823,1979.541341,1612.122336,1469.799294,1717.153670,1875.334736,1935.966318,2250.154659,1205.103140,1225.094749,1325.209587

In [16]:
df = df.dropna()

In [17]:
df.isna().sum()

Timestamp              0
Z11_CO2 (ppm)          0
Z12+13_CO2 (ppm)       0
Z15+16_CO2 (ppm)       0
Z17_CO2 (ppm)          0
Z1_CO2 (ppm)           0
Z21_CO2 (ppm)          0
Z22+23_CO2 (ppm)       0
Z24_CO2 (ppm)          0
Z25+26+27_CO2 (ppm)    0
Z31_CO2 (ppm)          0
Z32_CO2 (ppm)          0
Z33_CO2 (ppm)          0
Z3_CO2 (ppm)           0
Z4_CO2 (ppm)           0
Z5_CO2 (ppm)           0
dtype: int64

In [18]:
df.describe()

,Z11_CO2 (ppm),Z12+13_CO2 (ppm),Z15+16_CO2 (ppm),Z17_CO2 (ppm),Z1_CO2 (ppm),Z21_CO2 (ppm),Z22+23_CO2 (ppm),Z24_CO2 (ppm),Z25+26+27_CO2 (ppm),Z31_CO2 (ppm),Z32_CO2 (ppm),Z33_CO2 (ppm),Z3_CO2 (ppm),Z4_CO2 (ppm),Z5_CO2 (ppm)
count,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000
mean,519.579877,519.032249,531.866919,514.442317,529.777061,565.434874,540.273706,597.120300,544.110453,460.826620,523.581114,547.053373,519.771219,517.994912,512.778835
std,127.771146,123.147607,129.160309,118.794042,139.913064,187.723707,153.734987,134.653165,160.249560,126.380538,134.206155,178.828197,100.890085,109.011047,107.453650
min,372.496284,392.138658,392.320007,393.546666,390.570655,391.039987,390.479988,329.133568,346.267136,367.282759,393.925331,391.735990,391.557322,390.997322,392.445323
25%,437.362667,434.720002,446.345337,433.596003,442.378666,434.517335,431.774000,498.381333,435.813332,390.079987,432.790668,436.322667,451.849331,445.270670,436.684003
50%,471.850668,473.009333,485.717333,471.562666,485.920001,492.103999,480.512000,575.802665,481.946668,392.575993,476.037333,483.178667,487.626670,481.324359,473.879997
75%,558.701337,566.002669,572.538666,551.662672,568.555995,632.042666,599.434667,669.955993,592.769339,482.472001,569.605335,594.755999,554.570664,552.145328,559.898668
max,1786.037893,1674.273698,1677.911592,1563.688422,2843.415823,1979.541341,1612.122336,1469.799294,1717.153670,1875.334736,1935.966318,2250.154659,1205.103140,1225.094749,1325.209587

In [19]:
df.select_dtypes(include=['number']).corr()

,Z11_CO2 (ppm),Z12+13_CO2 (ppm),Z15+16_CO2 (ppm),Z17_CO2 (ppm),Z1_CO2 (ppm),Z21_CO2 (ppm),Z22+23_CO2 (ppm),Z24_CO2 (ppm),Z25+26+27_CO2 (ppm),Z31_CO2 (ppm),Z32_CO2 (ppm),Z33_CO2 (ppm),Z3_CO2 (ppm),Z4_CO2 (ppm),Z5_CO2 (ppm)
Z11_CO2 (ppm),1.000000,0.945421,0.901375,0.867233,0.824681,0.743020,0.894211,0.446013,0.898591,0.871996,0.904416,0.774407,0.809915,0.844571,0.772738
Z12+13_CO2 (ppm),0.945421,1.000000,0.959485,0.929085,0.896502,0.717815,0.877984,0.411662,0.867046,0.810658,0.868525,0.751488,0.877643,0.910874,0.859134
Z15+16_CO2 (ppm),0.901375,0.959485,1.000000,0.958336,0.866290,0.690330,0.845329,0.394052,0.825679,0.766451,0.831714,0.740177,0.882304,0.906191,0.867374
Z17_CO2 (ppm),0.867233,0.929085,0.958336,1.000000,0.829504,0.700422,0.837645,0.352807,0.816185,0.743828,0.820152,0.733497,0.899972,0.921876,0.875179
Z1_CO2 (ppm),0.824681,0.896502,0.866290,0.829504,1.000000,0.619622,0.765242,0.365879,0.750365,0.701214,0.753311,0.656218,0.824495,0.846023,0.779518
Z21_CO2 (ppm),0.743020,0.717815,0.690330,0.700422,0.619622,1.000000,0.838560,0.446791,0.815053,0.762154,0.787739,0.673235,0.625490,0.653951,0.572010
Z22+23_CO2 (ppm),0.894211,0.877984,0.845329,0.837645,0.765242,0.838560,1.000000,0.500187,0.962172,0.886034,0.930942,0.805331,0.770921,0.802422,0.720007
Z24_CO2 (ppm),0.446013,0.411662,0.394052,0.352807,0.365879,0.446791,0.500187,1.000000,0.555501,0.536960,0.527296,0.388617,0.359207,0.370218,0.292652
Z25+26+27_CO2 (ppm),0.898591,0.867046,0.825679,0.816185,0.750365,0.815053,0.962172,0.555501,1.000000,0.917791,0.950596,0.823175,0.759296,0.793396,0.701008
Z31_CO2 (ppm),0.871996,0.810658,0.766451,0.743828,0.701214,0.762154,0.886034,0.536960,0.917791,1.000000,0.936000,0.815293,0.684159,0.715081,0.625916
Z32_CO2 (ppm),0.904416,0.868525,0.831714,0.820152,0.753311,0.787739,0.930942,0.527296,0.950596,0.936000,1.000000,0.815341,0.755127,0.784737,0.711026
Z33_CO2 (ppm),0.774407,0.751488,0.740177,0.733497,0.656218,0.673235,0.805331,0.388617,0.823175,0.815293,0.815341,1.000000,0.679283,0.697689,0.644992
Z3_CO2 (ppm),0.809915,0.877643,0.882304,0.899972,0.824495,0.625490,0.770921,0.359207,0.759296,0.684159,0.755127,0.679283,1.000000,0.984159,0.876402
Z4_CO2 (ppm),0.844571,0.910874,0.906191,0.921876,0.846023,0.653951,0.802422,0.370218,0.793396,0.715081,0.784737,0.697689,0.984159,1.000000,0.887916
Z5_CO2 (ppm),0.772738,0.859134,0.867374,0.875179,0.779518,0.572010,0.720007,0.292652,0.701008,0.625916,0.711026,0.644992,0.876402,0.887916,1.000000

In [20]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df = df.set_index('Timestamp')

C:\Users\Noble Adike\AppData\Local\Temp\ipykernel_21176\330094659.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [21]:
def treat_outliers_iqr(df):
    df_clean = df.copy()
    for col in df_clean.columns:
        Q1 = df_clean[col].quantile(0.25)
        Q3 = df_clean[col].quantile(0.75)
        IQR = Q3 - Q1


        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        df_clean[col] = df_clean[col].clip(lower=lower_bound, upper=upper_bound)
    return df_clean
df = treat_outliers_iqr(df)

In [22]:
df.describe()

,Z11_CO2 (ppm),Z12+13_CO2 (ppm),Z15+16_CO2 (ppm),Z17_CO2 (ppm),Z1_CO2 (ppm),Z21_CO2 (ppm),Z22+23_CO2 (ppm),Z24_CO2 (ppm),Z25+26+27_CO2 (ppm),Z31_CO2 (ppm),Z32_CO2 (ppm),Z33_CO2 (ppm),Z3_CO2 (ppm),Z4_CO2 (ppm),Z5_CO2 (ppm)
count,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000,8778.000000
mean,510.433415,512.758879,523.224272,506.839447,519.908925,555.391863,532.882437,594.161652,533.146851,445.620667,515.725229,532.617359,513.815124,510.596885,508.634191
std,97.296905,101.979687,102.633206,96.053950,101.171996,155.710835,131.178784,124.709655,127.923991,80.810077,108.331709,127.127541,82.333789,86.554645,93.990401
min,372.496284,392.138658,392.320007,393.546666,390.570655,391.039987,390.479988,329.133568,346.267136,367.282759,393.925331,391.735990,391.557322,390.997322,392.445323
25%,437.362667,434.720002,446.345337,433.596003,442.378666,434.517335,431.774000,498.381333,435.813332,390.079987,432.790668,436.322667,451.849331,445.270670,436.684003
50%,471.850668,473.009333,485.717333,471.562666,485.920001,492.103999,480.512000,575.802665,481.946668,392.575993,476.037333,483.178667,487.626670,481.324359,473.879997
75%,558.701337,566.002669,572.538666,551.662672,568.555995,632.042666,599.434667,669.955993,592.769339,482.472001,569.605335,594.755999,554.570664,552.145328,559.898668
max,740.709342,762.926670,761.828661,728.762676,757.821988,928.330662,850.925669,927.317983,828.203351,621.060022,774.827334,832.405996,708.652663,712.457315,744.720667

In [23]:
scaler = StandardScaler()
numeric_cols = df.select_dtypes(include=['number']).columns
df_scaled = df.copy()
df_scaled[numeric_cols] = scaler.fit_transform(df_scaled[numeric_cols])

In [24]:
df_scaled.head()

,Z11_CO2 (ppm),Z12+13_CO2 (ppm),Z15+16_CO2 (ppm),Z17_CO2 (ppm),Z1_CO2 (ppm),Z21_CO2 (ppm),Z22+23_CO2 (ppm),Z24_CO2 (ppm),Z25+26+27_CO2 (ppm),Z31_CO2 (ppm),Z32_CO2 (ppm),Z33_CO2 (ppm),Z3_CO2 (ppm),Z4_CO2 (ppm),Z5_CO2 (ppm)
Timestamp,,,,,,,,,,,,,,,
2023-06-01 00:00:00-04:00,-0.831442,-0.837145,-0.795658,0.000256,-0.904435,-0.750733,-0.790679,-0.210605,-0.824955,-0.687338,-0.542881,-0.736216,1.303624,0.202987,-0.485349
2023-06-01 01:00:00-04:00,-0.784572,-0.790649,-0.779340,-0.266832,-0.907282,-0.745629,-0.801332,-0.178914,-0.829708,-0.687338,-0.647996,-0.762984,1.298377,0.603589,-0.718804
2023-06-01 02:00:00-04:00,-0.751297,-0.785210,-0.732569,-0.418366,-0.853245,-0.750972,-0.785881,-0.108902,-0.806818,-0.687338,-0.717761,-0.794995,0.892138,0.210320,-0.620746
2023-06-01 03:00:00-04:00,-0.778432,-0.738766,-0.743794,-0.568513,-0.812915,-0.737408,-0.792550,-0.583204,-0.835253,-0.687338,-0.770196,-0.788954,0.345518,-0.153309,-0.447272
2023-06-01 04:00:00-04:00,-0.723505,-0.682386,-0.756162,-0.628816,-0.793146,-0.755254,-0.811294,-0.768904,-0.826456,-0.687338,-0.786985,-0.777878,0.094882,-0.294115,-0.423041