In [25]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt 
import os
from sklearn.preprocessing import StandardScaler, LabelEncoder

In [5]:
path = r"C:\Users\Noble Adike\Desktop\Coding\KPMG\kpmg-1a\data\harvard\Year 1 (Jun 2022 - May 2023)\CO2_hourly\48190927_CO2_hourly.csv"
df = pd.read_csv(path)

In [6]:
df.head()

,Timestamp,Z11_CO2 (ppm),Z12+13_CO2 (ppm),Z15+16_CO2 (ppm),Z17_CO2 (ppm),Z1_CO2 (ppm),Z21_CO2 (ppm),Z22+23_CO2 (ppm),Z24_CO2 (ppm),Z25+26+27_CO2 (ppm),Z31_CO2 (ppm),Z32_CO2 (ppm),Z33_CO2 (ppm),Z3_CO2 (ppm),Z4_CO2 (ppm),Z5_CO2 (ppm)
0,2022-06-01 00:00:00-04:00,390.298654,429.973335,424.330668,418.773334,419.775998,390.079987,425.727998,481.850666,390.079987,390.079987,433.530666,439.096000,419.888000,390.079987,390.079987
1,2022-06-01 01:00:00-04:00,390.490655,431.637332,420.874667,416.133333,416.186667,390.079987,425.989333,570.848003,390.079987,390.079987,438.192001,447.456000,421.562665,390.079987,390.079987
2,2022-06-01 02:00:00-04:00,390.298655,434.879999,425.162667,419.594665,421.370665,390.079987,429.781333,667.210666,390.079987,390.079987,437.621336,447.413333,425.242667,391.093322,390.079987
3,2022-06-01 03:00:00-04:00,392.111991,441.034666,451.253333,433.226668,441.770669,390.079987,423.498669,607.349334,390.079987,390.079987,431.274666,443.205333,441.669335,396.975998,407.567995
4,2022-06-01 04:00:00-04:00,392.021326,449.050669,460.746666,446.704001,448.784000,390.079987,426.885334,425.258667,390.079987,390.079987,433.168001,444.960002,451.120001,412.650666,483.541336

In [7]:
df.isna().sum()

Timestamp                0
Z11_CO2 (ppm)          179
Z12+13_CO2 (ppm)       179
Z15+16_CO2 (ppm)       179
Z17_CO2 (ppm)          179
Z1_CO2 (ppm)           179
Z21_CO2 (ppm)          179
Z22+23_CO2 (ppm)       179
Z24_CO2 (ppm)          179
Z25+26+27_CO2 (ppm)    179
Z31_CO2 (ppm)          179
Z32_CO2 (ppm)          179
Z33_CO2 (ppm)          179
Z3_CO2 (ppm)           179
Z4_CO2 (ppm)           179
Z5_CO2 (ppm)           179
dtype: int64

In [8]:
df.describe()

,Z11_CO2 (ppm),Z12+13_CO2 (ppm),Z15+16_CO2 (ppm),Z17_CO2 (ppm),Z1_CO2 (ppm),Z21_CO2 (ppm),Z22+23_CO2 (ppm),Z24_CO2 (ppm),Z25+26+27_CO2 (ppm),Z31_CO2 (ppm),Z32_CO2 (ppm),Z33_CO2 (ppm),Z3_CO2 (ppm),Z4_CO2 (ppm),Z5_CO2 (ppm)
count,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000
mean,492.511989,516.508762,532.954582,513.445270,524.050053,492.175292,540.712446,582.223867,499.828979,457.250130,518.601113,538.537080,520.230935,502.653011,491.894434
std,129.426412,118.590010,129.946652,119.696262,136.259767,148.687610,151.790644,144.593472,159.733189,127.459484,127.872837,156.754530,102.782196,114.419835,110.049354
min,390.079987,391.269322,390.079987,390.671988,391.013323,390.079987,391.093323,390.079987,390.079987,390.079987,391.967994,391.727991,393.866665,390.079987,390.079987
25%,412.981331,437.834665,445.685338,434.896001,437.520001,390.079987,435.146667,469.680015,390.079987,390.079987,432.714668,439.317332,450.096001,426.394667,418.815997
50%,447.610663,476.309332,488.085334,476.821333,477.157334,429.173335,482.501337,562.434671,435.802667,391.205323,471.338664,481.775999,494.837339,475.029331,461.093333
75%,522.656006,557.429336,582.511303,549.797334,568.021328,530.282672,596.250679,664.048003,533.237338,471.541334,563.461333,584.346668,560.197336,545.471998,534.069336
max,1494.336015,1402.346670,1473.962671,1487.168005,2498.062229,1682.858667,1496.106671,1365.866674,1502.912002,1677.482674,1776.895988,2012.405110,1514.069334,1538.965346,2413.037714

In [9]:
df = df.dropna()

In [11]:
df.isna().sum()

Timestamp              0
Z11_CO2 (ppm)          0
Z12+13_CO2 (ppm)       0
Z15+16_CO2 (ppm)       0
Z17_CO2 (ppm)          0
Z1_CO2 (ppm)           0
Z21_CO2 (ppm)          0
Z22+23_CO2 (ppm)       0
Z24_CO2 (ppm)          0
Z25+26+27_CO2 (ppm)    0
Z31_CO2 (ppm)          0
Z32_CO2 (ppm)          0
Z33_CO2 (ppm)          0
Z3_CO2 (ppm)           0
Z4_CO2 (ppm)           0
Z5_CO2 (ppm)           0
dtype: int64

In [15]:
df.describe()

,Z11_CO2 (ppm),Z12+13_CO2 (ppm),Z15+16_CO2 (ppm),Z17_CO2 (ppm),Z1_CO2 (ppm),Z21_CO2 (ppm),Z22+23_CO2 (ppm),Z24_CO2 (ppm),Z25+26+27_CO2 (ppm),Z31_CO2 (ppm),Z32_CO2 (ppm),Z33_CO2 (ppm),Z3_CO2 (ppm),Z4_CO2 (ppm),Z5_CO2 (ppm)
count,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000
mean,492.511989,516.508762,532.954582,513.445270,524.050053,492.175292,540.712446,582.223867,499.828979,457.250130,518.601113,538.537080,520.230935,502.653011,491.894434
std,129.426412,118.590010,129.946652,119.696262,136.259767,148.687610,151.790644,144.593472,159.733189,127.459484,127.872837,156.754530,102.782196,114.419835,110.049354
min,390.079987,391.269322,390.079987,390.671988,391.013323,390.079987,391.093323,390.079987,390.079987,390.079987,391.967994,391.727991,393.866665,390.079987,390.079987
25%,412.981331,437.834665,445.685338,434.896001,437.520001,390.079987,435.146667,469.680015,390.079987,390.079987,432.714668,439.317332,450.096001,426.394667,418.815997
50%,447.610663,476.309332,488.085334,476.821333,477.157334,429.173335,482.501337,562.434671,435.802667,391.205323,471.338664,481.775999,494.837339,475.029331,461.093333
75%,522.656006,557.429336,582.511303,549.797334,568.021328,530.282672,596.250679,664.048003,533.237338,471.541334,563.461333,584.346668,560.197336,545.471998,534.069336
max,1494.336015,1402.346670,1473.962671,1487.168005,2498.062229,1682.858667,1496.106671,1365.866674,1502.912002,1677.482674,1776.895988,2012.405110,1514.069334,1538.965346,2413.037714

In [18]:
df.select_dtypes(include=['number']).corr()

,Z11_CO2 (ppm),Z12+13_CO2 (ppm),Z15+16_CO2 (ppm),Z17_CO2 (ppm),Z1_CO2 (ppm),Z21_CO2 (ppm),Z22+23_CO2 (ppm),Z24_CO2 (ppm),Z25+26+27_CO2 (ppm),Z31_CO2 (ppm),Z32_CO2 (ppm),Z33_CO2 (ppm),Z3_CO2 (ppm),Z4_CO2 (ppm),Z5_CO2 (ppm)
Z11_CO2 (ppm),1.000000,0.932310,0.881512,0.854087,0.826807,0.809315,0.883954,0.463257,0.911407,0.876037,0.885905,0.870447,0.735597,0.754093,0.778841
Z12+13_CO2 (ppm),0.932310,1.000000,0.954764,0.915297,0.905446,0.685617,0.898688,0.385261,0.823263,0.821242,0.862098,0.862931,0.842727,0.790002,0.856925
Z15+16_CO2 (ppm),0.881512,0.954764,1.000000,0.948103,0.893283,0.643466,0.867562,0.375282,0.784075,0.781080,0.820672,0.826875,0.855209,0.797093,0.874364
Z17_CO2 (ppm),0.854087,0.915297,0.948103,1.000000,0.838527,0.652099,0.851709,0.330468,0.782178,0.752912,0.781952,0.797253,0.865038,0.802900,0.870895
Z1_CO2 (ppm),0.826807,0.905446,0.893283,0.838527,1.000000,0.600408,0.808998,0.342179,0.731502,0.743663,0.771116,0.782604,0.814747,0.808332,0.799475
Z21_CO2 (ppm),0.809315,0.685617,0.643466,0.652099,0.600408,1.000000,0.767747,0.519027,0.880875,0.800278,0.783043,0.749292,0.509544,0.591227,0.554923
Z22+23_CO2 (ppm),0.883954,0.898688,0.867562,0.851709,0.808998,0.767747,1.000000,0.460827,0.894246,0.857963,0.910271,0.892255,0.766162,0.729379,0.763114
Z24_CO2 (ppm),0.463257,0.385261,0.375282,0.330468,0.342179,0.519027,0.460827,1.000000,0.546461,0.529134,0.496150,0.479492,0.313888,0.399332,0.305661
Z25+26+27_CO2 (ppm),0.911407,0.823263,0.784075,0.782178,0.731502,0.880875,0.894246,0.546461,1.000000,0.906781,0.907861,0.892778,0.654349,0.704065,0.681317
Z31_CO2 (ppm),0.876037,0.821242,0.781080,0.752912,0.743663,0.800278,0.857963,0.529134,0.906781,1.000000,0.914601,0.900196,0.642729,0.658523,0.669040
Z32_CO2 (ppm),0.885905,0.862098,0.820672,0.781952,0.771116,0.783043,0.910271,0.496150,0.907861,0.914601,1.000000,0.929364,0.681827,0.670403,0.698632
Z33_CO2 (ppm),0.870447,0.862931,0.826875,0.797253,0.782604,0.749292,0.892255,0.479492,0.892778,0.900196,0.929364,1.000000,0.705981,0.686993,0.716666
Z3_CO2 (ppm),0.735597,0.842727,0.855209,0.865038,0.814747,0.509544,0.766162,0.313888,0.654349,0.642729,0.681827,0.705981,1.000000,0.911852,0.844406
Z4_CO2 (ppm),0.754093,0.790002,0.797093,0.802900,0.808332,0.591227,0.729379,0.399332,0.704065,0.658523,0.670403,0.686993,0.911852,1.000000,0.783926
Z5_CO2 (ppm),0.778841,0.856925,0.874364,0.870895,0.799475,0.554923,0.763114,0.305661,0.681317,0.669040,0.698632,0.716666,0.844406,0.783926,1.000000

In [20]:
df['Timestamp'] = pd.to_datetime(df['Timestamp'])
df = df.set_index('Timestamp')

C:\Users\Noble Adike\AppData\Local\Temp\ipykernel_23332\330094659.py:1: FutureWarning: In a future version of pandas, parsing datetimes with mixed time zones will raise an error unless `utc=True`. Please specify `utc=True` to opt in to the new behaviour and silence this warning. To create a `Series` with mixed offsets and `object` dtype, please use `apply` and `datetime.datetime.strptime`
  df['Timestamp'] = pd.to_datetime(df['Timestamp'])

In [21]:
def treat_outliers_iqr(df):
    df_clean = df.copy()
    for col in df_clean.columns:
        Q1 = df_clean[col].quantile(0.25)
        Q3 = df_clean[col].quantile(0.75)
        IQR = Q3 - Q1


        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        df_clean[col] = df_clean[col].clip(lower=lower_bound, upper=upper_bound)
    return df_clean
df = treat_outliers_iqr(df)

In [23]:
df.describe()

,Z11_CO2 (ppm),Z12+13_CO2 (ppm),Z15+16_CO2 (ppm),Z17_CO2 (ppm),Z1_CO2 (ppm),Z21_CO2 (ppm),Z22+23_CO2 (ppm),Z24_CO2 (ppm),Z25+26+27_CO2 (ppm),Z31_CO2 (ppm),Z32_CO2 (ppm),Z33_CO2 (ppm),Z3_CO2 (ppm),Z4_CO2 (ppm),Z5_CO2 (ppm)
count,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000,8581.000000
mean,480.284074,509.077676,525.684377,504.879547,514.907056,480.121489,532.453625,579.726467,485.092920,439.202707,511.336320,526.190038,514.978015,496.173912,486.038084
std,89.467738,92.605660,104.747105,89.790619,101.769872,113.823337,126.080921,135.973411,115.839268,73.122133,102.969973,116.053834,82.573004,90.034658,85.917215
min,390.079987,391.269322,390.079987,390.671988,391.013323,390.079987,391.093323,390.079987,390.079987,390.079987,391.967994,391.727991,393.866665,390.079987,390.079987
25%,412.981331,437.834665,445.685338,434.896001,437.520001,390.079987,435.146667,469.680015,390.079987,390.079987,432.714668,439.317332,450.096001,426.394667,418.815997
50%,447.610663,476.309332,488.085334,476.821333,477.157334,429.173335,482.501337,562.434671,435.802667,391.205323,471.338664,481.775999,494.837339,475.029331,461.093333
75%,522.656006,557.429336,582.511303,549.797334,568.021328,530.282672,596.250679,664.048003,533.237338,471.541334,563.461333,584.346668,560.197336,545.471998,534.069336
max,687.168018,736.821341,787.750250,722.149333,763.773317,740.586700,837.906696,955.599986,747.973366,593.733355,759.581331,801.890673,725.349338,724.087995,706.949344

In [26]:
scaler = StandardScaler()
numeric_cols = df.select_dtypes(include=['number']).columns
df_scaled = df.copy()
df_scaled[numeric_cols] = scaler.fit_transform(df_scaled[numeric_cols])

In [27]:
df_scaled.head()

,Z11_CO2 (ppm),Z12+13_CO2 (ppm),Z15+16_CO2 (ppm),Z17_CO2 (ppm),Z1_CO2 (ppm),Z21_CO2 (ppm),Z22+23_CO2 (ppm),Z24_CO2 (ppm),Z25+26+27_CO2 (ppm),Z31_CO2 (ppm),Z32_CO2 (ppm),Z33_CO2 (ppm),Z3_CO2 (ppm),Z4_CO2 (ppm),Z5_CO2 (ppm)
Timestamp,,,,,,,,,,,,,,,
2022-06-01 00:00:00-04:00,-1.005845,-0.854256,-0.967660,-0.959023,-0.934821,-0.79111,-0.846534,-0.719858,-0.820261,-0.671829,-0.755659,-0.750506,-1.151654,-1.178436,-1.116932
2022-06-01 01:00:00-04:00,-1.003699,-0.836286,-1.000656,-0.988426,-0.970092,-0.79111,-0.844462,-0.065299,-0.820261,-0.671829,-0.710388,-0.678466,-1.131372,-1.178436,-1.116932
2022-06-01 02:00:00-04:00,-1.005845,-0.801269,-0.959717,-0.949875,-0.919151,-0.79111,-0.814384,0.643429,-0.820261,-0.671829,-0.715930,-0.678834,-1.086803,-1.167181,-1.116932
2022-06-01 03:00:00-04:00,-0.985576,-0.734804,-0.710620,-0.798046,-0.718687,-0.79111,-0.864217,0.203161,-0.820261,-0.671829,-0.777570,-0.715095,-0.887856,-1.101839,-0.913375
2022-06-01 04:00:00-04:00,-0.986589,-0.648238,-0.619984,-0.647940,-0.649769,-0.79111,-0.837355,-1.136081,-0.820261,-0.671829,-0.759181,-0.699975,-0.773397,-0.927733,-0.029062